default_stages: [commit, push]
fail_fast: true
repos:
  - repo: https://github.com/pycqa/isort
    rev: '5.9.3'
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: '21.9b0'
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
      - id: flake8
